export const LAB_FRAMES = [
  {
    id: "origin",
    label: "Camera grammar",
    x: 0,
    y: 0,
    w: 920,
    h: 600,
    surface: "none",
    shape: "circle",
    transition: { preset: "glide", duration: "auto" },
    data: {
      kind: "origin",
      index: "00",
      eyebrow: "ZOOMSTAGE / MOTION LANGUAGE",
      title: "The camera is the interface.",
      body: "Five trajectories, independent focus geometry and surfaces that no longer need to look like slides.",
    },
  },
  {
    id: "arc-field",
    label: "Arc trajectory field",
    x: 1420,
    y: -620,
    w: 620,
    h: 620,
    rotate: -8,
    surface: "none",
    shape: "circle",
    transition: { preset: "arc", duration: "auto", curve: 0.34 },
    data: {
      kind: "arc",
      index: "01",
      eyebrow: "CURVED TRANSLATION",
      title: "Arc",
      body: "The subject follows a deliberate curve instead of crossing the canvas on a mechanical diagonal.",
    },
  },
  {
    id: "dolly-gate",
    label: "Dolly depth gate",
    x: 2700,
    y: 260,
    w: 1060,
    h: 440,
    rotate: 4,
    surface: "glass",
    shape: "pill",
    transition: { preset: "dolly", duration: "auto", lift: 0.28 },
    data: {
      kind: "dolly",
      index: "02",
      eyebrow: "DEPTH BEFORE DISTANCE",
      title: "Dolly",
      body: "The camera creates breathing room, travels across the world and then commits to the destination.",
    },
  },
  {
    id: "orbit-core",
    label: "Orbit camera core",
    x: 1640,
    y: 1420,
    w: 700,
    h: 700,
    rotate: 9,
    surface: "none",
    clipPath: "polygon(25% 5%, 75% 5%, 98% 50%, 75% 95%, 25% 95%, 2% 50%)",
    transition: { preset: "orbit", duration: "auto", curve: -0.3, roll: 12 },
    data: {
      kind: "orbit",
      index: "03",
      eyebrow: "POSITION + ATTITUDE",
      title: "Orbit",
      body: "A curved route and restrained camera roll make spatial relationships visible without spinning the audience.",
    },
  },
  {
    id: "focus-array",
    label: "Independent focus array",
    x: -760,
    y: 1260,
    w: 1180,
    h: 720,
    rotate: -4,
    surface: "none",
    camera: {
      x: -390,
      y: 1450,
      w: 380,
      h: 300,
      rotate: -4,
      padding: 0.15,
      zoom: 0.92,
    },
    transition: { preset: "focus", duration: "auto", lift: 0.1 },
    data: {
      kind: "focus",
      index: "04",
      eyebrow: "SURFACE ≠ CAMERA TARGET",
      title: "Focus",
      body: "The visible scene remains large while the camera selects one precise instrument inside it.",
    },
  },
];

export const PRESET_LABELS = {
  glide: "Glide",
  arc: "Arc",
  dolly: "Dolly",
  orbit: "Orbit",
  focus: "Focus",
};
