export const VITRA_FRAMES = [
  {
    id: "threshold",
    label: "Threshold",
    x: 0, y: 0, w: 980, h: 720,
    surface: "none",
    shape: "circle",
    camera: { x: 0, y: 0, w: 980, h: 720, padding: 0.14 },
    compact: { x: 0, y: 0, w: 390, h: 620, rotate: 0, camera: null },
    transition: { preset: "glide", duration: "auto" },
    data: {
      kind: "threshold",
      image: "./assets/threshold-pressure-cell.webp",
      index: "00",
      eyebrow: "VITRA / MATERIAL SYSTEM",
      title: "Matter remembers pressure.",
      body: "A six-stage study in stainless steel, transparent structure and one controlled red signal.",
      contrastText: "transparent structure",
    },
  },
  {
    id: "vessel",
    label: "Glass vessel",
    x: 1150, y: -420, w: 920, h: 540, rotate: -5,
    surface: "glass",
    shape: "pill",
    camera: { x: 1150, y: -420, w: 920, h: 540, padding: 0.14 },
    compact: { x: 500, y: -150, w: 390, h: 620, rotate: -3, camera: null },
    transition: { preset: "arc", duration: "auto", curve: 0.3 },
    data: {
      kind: "vessel",
      image: "./assets/glass-vessel.webp",
      index: "01",
      eyebrow: "BOROSILICATE / 11.8 MM",
      title: "Nothing hidden.",
      body: "The vessel exposes the force it contains. Transparency becomes an engineering promise, not decoration.",
    },
  },
  {
    id: "pressure",
    label: "Pressure signal",
    x: 2400, y: 200, w: 720, h: 720, rotate: 6,
    surface: "none",
    shape: "circle",
    camera: { x: 2400, y: 200, w: 720, h: 720, padding: 0.14 },
    compact: { x: 1000, y: 100, w: 390, h: 620, rotate: 4, camera: null },
    transition: { preset: "dolly", duration: "auto", lift: 0.24 },
    data: {
      kind: "pressure",
      image: "./assets/pressure-gauge.webp",
      index: "02",
      eyebrow: "LOAD / SIGNAL",
      title: "Pressure becomes language.",
      body: "One red line carries urgency through a field of quiet steel.",
    },
  },
  {
    id: "assembly",
    label: "Seal assembly",
    x: 1400, y: 1150, w: 1050, h: 650, rotate: 2,
    surface: "glass",
    camera: { x: 1400, y: 1150, w: 1050, h: 650, padding: 0.14 },
    compact: { x: 900, y: 800, w: 390, h: 680, rotate: 1, camera: null },
    transition: { preset: "orbit", duration: "auto", curve: -0.22, roll: 8 },
    data: {
      kind: "assembly",
      image: "./assets/seal-assembly.webp",
      sealedImage: "./assets/seal-assembled.webp",
      index: "03",
      eyebrow: "INTERLOCK / USER CONTROLLED",
      title: "A seal is choreography.",
      body: "Three pieces meet with visible intent. Engage the mechanism when the camera settles.",
    },
  },
  {
    id: "refraction",
    label: "Refraction field",
    x: 250, y: 1320, w: 760, h: 760, rotate: -7,
    surface: "none",
    clipPath: "polygon(14% 4%, 86% 4%, 98% 50%, 86% 96%, 14% 96%, 2% 50%)",
    compact: { x: 400, y: 900, w: 390, h: 650, rotate: -4 },
    transition: { preset: "focus", duration: "auto", lift: 0.12 },
    data: {
      kind: "refraction",
      image: "./assets/refraction-bench.webp",
      index: "04",
      eyebrow: "OPTICS / CONTROLLED DEVIATION",
      title: "Light changes direction.",
      body: "Glass does not erase the signal. It bends the path and makes the route legible.",
    },
  },
  {
    id: "protocol",
    label: "Final protocol",
    x: -720, y: 650, w: 1180, h: 760, rotate: -3,
    surface: "none",
    camera: { x: -500, y: 590, w: 760, h: 880, rotate: -3, padding: 0.1, zoom: 0.95 },
    compact: { x: -100, y: 700, w: 390, h: 650, rotate: -2, camera: null },
    transition: { preset: "focus", duration: "auto", lift: 0.08 },
    data: {
      kind: "protocol",
      image: "./assets/final-protocol-system.webp",
      index: "05",
      eyebrow: "VITRA / CLOSED SYSTEM",
      title: "The loop closes without a seam.",
      body: "Camera, material and motion resolve into one controlled interface.",
    },
  },
];

export const PROTOCOL_READOUTS = [
  { label: "Vessel integrity", value: "99.98%" },
  { label: "Seal pressure", value: "86 kN" },
  { label: "Optical drift", value: "0.04°" },
];
