const asset = (name) => new URL(`./assets/${name}`, import.meta.url).href;

export const COURSES = [
  {
    id: "aperitivo",
    course: "01 / APERITIVO",
    time: "19:08",
    title: "Wake the palate.",
    body: "A bright first sip: bitter botanicals, cold glass and an orange peel releasing its perfume into the room.",
    note: "Orange · bitter herbs · ice",
    tags: ["BITTER", "CITRUS", "COLD"],
    image: asset("aperitivo.jpg"),
    alt: "Amber cocktail glowing against a dark background",
    credit: "Unsplash / Andrea Riezzo",
    source: "https://unsplash.com/photos/clear-drinking-glass-with-orange-liquid-and-ice-1hKZ0A182Bk",
    tone: "amber",
    side: "left",
  },
  {
    id: "garden",
    course: "02 / GARDEN",
    time: "19:42",
    title: "Color has a flavor.",
    body: "Heirloom tomatoes arrive almost untouched. Sun, salt and acidity do the talking; everything else steps aside.",
    note: "Tomato · sea salt · green oil",
    tags: ["JUICY", "GREEN", "BRIGHT"],
    image: asset("garden.jpg"),
    alt: "A colorful market selection of heirloom tomatoes",
    credit: "Unsplash / Anda Ambrosini",
    source: "https://unsplash.com/photos/bunch-of-tomatoes-UOEB1ztsDMo",
    tone: "tomato",
    side: "right",
  },
  {
    id: "sushi",
    course: "03 / TIDE",
    time: "20:16",
    title: "Precision, served quietly.",
    body: "Rice, seaweed and clean cuts. The smallest course carries the sharpest rhythm: soft, crisp, saline, still.",
    note: "Rice · nori · ginger",
    tags: ["UMAMI", "SALINE", "CLEAN"],
    image: asset("sushi.jpg"),
    alt: "Maki sushi arranged on a white platter",
    credit: "Unsplash / Emy",
    source: "https://unsplash.com/photos/neatly-presented-sushi-on-plate-5Gte2_TlS_A",
    tone: "wasabi",
    side: "left",
  },
  {
    id: "carbonara",
    course: "04 / HANDMADE",
    time: "21:03",
    title: "Comfort, with discipline.",
    body: "Silky pasta, aged cheese and black pepper. Familiar ingredients become exact when texture leads every decision.",
    note: "Pasta · pecorino · pepper",
    tags: ["SILKY", "WARM", "SAVORY"],
    image: asset("carbonara.jpg"),
    alt: "Creamy pasta served on handmade ceramic plates",
    credit: "Unsplash / Bruna Branco",
    source: "https://unsplash.com/photos/pasta-on-plate-with-fork-t8hTmte4O_g",
    tone: "cream",
    side: "right",
  },
  {
    id: "ember",
    course: "05 / EMBER",
    time: "21:27",
    title: "Fire makes its mark.",
    body: "A deep crust, a rosy center and rosemary carried through brown butter. Heat becomes flavor when timing is exact.",
    note: "Beef · rosemary · brown butter",
    tags: ["CHARRED", "JUICY", "SMOKE"],
    image: asset("ember.jpg"),
    alt: "Seared filet mignon with rosemary and brown butter",
    credit: "Unsplash / Chad Montano",
    source: "https://unsplash.com/photos/beef-steak-with-fork-M0lUxgLnlfk",
    tone: "ember",
    side: "left",
  },
  {
    id: "wine",
    course: "06 / PAIRING",
    time: "21:52",
    title: "Let the glass move.",
    body: "A red wine caught between stillness and motion. Dark fruit opens first; spice and tannin lengthen the finish.",
    note: "Cherry · cedar · long finish",
    tags: ["DEEP", "DRY", "VELVET"],
    image: asset("wine.jpg"),
    alt: "Red wine splashing dramatically around a glass",
    credit: "Unsplash / Saman Taheri",
    source: "https://unsplash.com/photos/red-wine-in-clear-wine-glass-MXMs8q2OjeA",
    tone: "wine",
    side: "right",
  },
  {
    id: "cheese",
    course: "07 / FROMAGE",
    time: "22:18",
    title: "Time is an ingredient.",
    body: "Soft, blue and aged cheeses share the board with fruit and patience. Every texture carries a different clock.",
    note: "Brie · blue · aged reserve",
    tags: ["AGED", "CREAMY", "FUNK"],
    image: asset("cheese.jpg"),
    alt: "Cheese and charcuterie board with fruit and wine",
    credit: "Unsplash / Daniel Silva Gaxiola",
    source: "https://unsplash.com/photos/a-wooden-board-topped-with-lots-of-different-types-of-cheese-meACam3ctq0",
    tone: "cheese",
    side: "left",
  },
  {
    id: "dessert",
    course: "08 / DESSERT",
    time: "22:43",
    title: "End on a dark note.",
    body: "Chocolate closes the menu with restraint: a thin shell, soft center and just enough bitterness to invite one last bite.",
    note: "Cacao · cream · toasted nut",
    tags: ["DARK", "SOFT", "SWEET"],
    image: asset("dessert.jpg"),
    alt: "A refined slice of chocolate cake on a white plate",
    credit: "Unsplash / Olga Petnyunene",
    source: "https://unsplash.com/photos/a-piece-of-chocolate-dessert-on-a-plate-with-a-fork-sNBnvtHjElM",
    tone: "cacao",
    side: "right",
  },
  {
    id: "coffee",
    course: "09 / AFTER",
    time: "23:02",
    title: "Pause for the ritual.",
    body: "Espresso arrives with no decoration. Pressure, heat and a few precise seconds turn roasted seeds into a final burst of energy.",
    note: "Cacao · caramel · roasted nut",
    tags: ["ROASTED", "HOT", "BOLD"],
    image: asset("coffee.jpg"),
    alt: "Espresso pouring from a machine into a dark cup",
    credit: "Unsplash / Daniel Lincoln",
    source: "https://unsplash.com/photos/espresso-machine-brewing-dark-coffee-into-glass-hb4PfjANoPg",
    tone: "coffee",
    side: "left",
  },
  {
    id: "nightcap",
    course: "10 / NIGHTCAP",
    time: "23:24",
    title: "One for the road.",
    body: "Bourbon, bitters, cherry and orange. The menu ends where the night continues — slowly, warmly and without a deadline.",
    note: "Bourbon · bitters · cherry",
    tags: ["WARM", "SPICED", "SLOW"],
    image: asset("nightcap.jpg"),
    alt: "Bourbon cocktail with cherries on a dark bar",
    credit: "Unsplash / Hybrid Storytellers",
    source: "https://unsplash.com/photos/a-cocktail-with-cherries-and-orange-peel-on-a-bar-oyaeXz5OZCY",
    tone: "night",
    side: "right",
  },
];

export const TABLE_GEOMETRY = [
  { x: 0, y: 0, w: 1280, h: 760, rotate: 0 },
  { x: 1500, y: -650, w: 1280, h: 760, rotate: -6 },
  { x: 3150, y: -400, w: 1280, h: 760, rotate: 5 },
  { x: 4600, y: 400, w: 1280, h: 760, rotate: -5 },
  { x: 5100, y: 1800, w: 1280, h: 760, rotate: 6 },
  { x: 4200, y: 3050, w: 1280, h: 760, rotate: -4 },
  { x: 2600, y: 3600, w: 1280, h: 760, rotate: 5 },
  { x: 900, y: 3300, w: 1280, h: 760, rotate: -6 },
  { x: -700, y: 2450, w: 1280, h: 760, rotate: 5 },
  { x: -1550, y: 1000, w: 1280, h: 760, rotate: -4 },
];
