const asset = (name) => new URL(`./assets/${name}`, import.meta.url).href;

export const SCENES = [
  {
    id: "departure",
    chapter: "01 / DEPARTURE",
    title: "Leave the familiar behind.",
    body: "Every journey begins by overcoming gravity. Artemis I turned night into day and opened a new path toward the Moon.",
    fact: "8.8 million pounds of thrust",
    distance: "T+00:00:00",
    image: asset("artemis-launch.jpg"),
    alt: "NASA Space Launch System rocket lifting off at night",
    credit: "NASA / Joel Kowsky",
    source: "https://www.nasa.gov/humans-in-space/view-the-best-images-from-nasas-artemis-i-mission/",
    tone: "amber",
  },
  {
    id: "orbit",
    chapter: "02 / HOME ORBIT",
    title: "See home as one world.",
    body: "From above, borders disappear. Weather, oceans, deserts, and cities become a single living system suspended in darkness.",
    fact: "12,742 km in diameter",
    distance: "ALT 35,786 KM",
    image: asset("blue-marble.jpg"),
    alt: "NASA Blue Marble view of Earth",
    credit: "NASA / NOAA / GSFC / Suomi NPP",
    source: "https://science.nasa.gov/image-detail/amf-gsfc_20171208_archive_e001386/",
    tone: "cyan",
  },
  {
    id: "lunar",
    chapter: "03 / LUNAR GATEWAY",
    title: "The Moon becomes a doorway.",
    body: "Orion looks back at Earth and the Moon together — two worlds aligned inside an ocean of black.",
    fact: "384,400 km from Earth",
    distance: "LOS 1.28 SEC",
    image: asset("earth-moon.jpg"),
    alt: "Orion spacecraft with Earth and Moon visible in the distance",
    credit: "NASA / Artemis I",
    source: "https://www.nasa.gov/humans-in-space/view-the-best-images-from-nasas-artemis-i-mission/",
    tone: "silver",
  },
  {
    id: "mars",
    chapter: "04 / MARS",
    title: "Follow the memory of water.",
    body: "At Jezero Crater, Perseverance reads an ancient river delta layer by layer, searching for evidence of a once-habitable world.",
    fact: "Sol 466 · Jezero Delta",
    distance: "225M KM FROM HOME",
    image: asset("mars-jezero.jpg"),
    alt: "Panorama of the ancient river delta in Mars Jezero Crater",
    credit: "NASA / JPL-Caltech / ASU / MSSS",
    source: "https://www.jpl.nasa.gov/images/pia24921-detailed-panorama-of-mars-jezero-crater-delta/",
    tone: "rust",
  },
  {
    id: "saturn",
    chapter: "05 / OUTER SYSTEM",
    title: "Enter the realm of rings.",
    body: "Webb sees Saturn in infrared light: an atmospheric world encircled by ice, accompanied by a family of distant moons.",
    fact: "146 moons and counting",
    distance: "1.4B KM FROM HOME",
    image: asset("saturn-webb.jpg"),
    alt: "James Webb infrared image of Saturn and several moons",
    credit: "NASA / ESA / CSA / STScI",
    source: "https://science.nasa.gov/asset/webb/saturn-webb-nircam-wide-image/",
    tone: "violet",
  },
  {
    id: "deep-space",
    chapter: "06 / DEEP SPACE",
    title: "Arrive where stars are born.",
    body: "The Cosmic Cliffs are not mountains. They are a wall of gas and dust, sculpted by newborn stars 7,600 light-years away.",
    fact: "NGC 3324 · Carina Nebula",
    distance: "7,600 LIGHT-YEARS",
    image: asset("cosmic-cliffs.png"),
    alt: "James Webb view of the Cosmic Cliffs in the Carina Nebula",
    credit: "NASA / ESA / CSA / STScI",
    source: "https://science.nasa.gov/asset/webb/cosmic-cliffs-in-the-carina-nebula-nircam-and-miri-composite-image/",
    tone: "nebula",
  },
];

export const FRAME_GEOMETRY = [
  { x: 0, y: 0, w: 1280, h: 760, rotate: 0 },
  { x: 1660, y: -520, w: 1120, h: 760, rotate: -7 },
  { x: 3020, y: 340, w: 1240, h: 760, rotate: 5 },
  { x: 2180, y: 1510, w: 1320, h: 760, rotate: -4 },
  { x: 440, y: 1710, w: 1320, h: 760, rotate: 7 },
  { x: -1420, y: 930, w: 1420, h: 800, rotate: -5 },
];
