export const SOURCE_DOCUMENTS = Object.freeze({
  "ai-spec": {
    title: "AI Reference Spec",
    description: "The complete source of truth for AI assistants generating FluxaWay applications.",
    path: "/docs/AI_SPEC.md",
    mode: "markdown",
    backLabel: "AI & security",
    backPath: "/ai-security",
  },
  "ai-qa": {
    title: "AI QA Runbook",
    description: "The browser-first process for validating FluxaWay changes and generated applications.",
    path: "/docs/AI_QA.md",
    mode: "markdown",
    backLabel: "AI & security",
    backPath: "/ai-security",
  },
  "motion-guide": {
    title: "FluxaWay Motion Guide",
    description: "The complete guide to timelines, keyframes, easing, staggering and motion accessibility.",
    path: "/docs/MOTION.md",
    mode: "markdown",
    backLabel: "FluxaWay Motion",
    backPath: "/addons/fluxaway-motion",
  },
  "motion-runtime-example": {
    title: "Runtime showcase source",
    description: "The primary application entry for the FluxaWay Motion runtime showcase.",
    path: "/examples/fluxaway-motion/app.js",
    mode: "javascript",
    backLabel: "FluxaWay Motion",
    backPath: "/addons/fluxaway-motion",
    previewPath: "/examples/fluxaway-motion/",
    previewLabel: "Open runtime showcase",
  },
  "motion-presentation-example": {
    title: "Motion presentation source",
    description: "The master-timeline entry for a fixed-stage presentation built without ZoomStage.",
    path: "/examples/motion-presentation/app.js",
    mode: "javascript",
    backLabel: "FluxaWay Motion",
    backPath: "/addons/fluxaway-motion",
    previewPath: "/examples/motion-presentation/",
    previewLabel: "Open Motion presentation",
  },
  "motion-editor-example": {
    title: "Motion editor source",
    description: "The primary application entry for the interactive FluxaWay Motion editor.",
    path: "/examples/motion-editor/app.js",
    mode: "javascript",
    backLabel: "FluxaWay Motion",
    backPath: "/addons/fluxaway-motion",
    previewPath: "/examples/motion-editor/",
    previewLabel: "Open Motion editor",
  },
  "architecture-example": {
    title: "Architecture presentation source",
    description: "The primary application entry for the FluxaWay architecture presentation.",
    path: "/examples/fluxaway-architecture/app.js",
    mode: "javascript",
    backLabel: "ZoomStage",
    backPath: "/addons/zoom-stage",
    previewPath: "/examples/fluxaway-architecture/",
    previewLabel: "Open presentation",
  },
  "atlas-example": {
    title: "Atlas presentation source",
    description: "The primary application entry for the FluxaWay Atlas presentation.",
    path: "/examples/fluxaway-atlas/app.js",
    mode: "javascript",
    backLabel: "ZoomStage",
    backPath: "/addons/zoom-stage",
    previewPath: "/examples/fluxaway-atlas/",
    previewLabel: "Open presentation",
  },
  "star-atlas-example": {
    title: "Free-zoom star atlas source",
    description: "The primary application entry for the free-zoom star atlas example.",
    path: "/examples/star-atlas/app.js",
    mode: "javascript",
    backLabel: "ZoomStage",
    backPath: "/addons/zoom-stage",
    previewPath: "/examples/star-atlas/",
    previewLabel: "Open star atlas",
  },
  "zoom-lab-example": {
    title: "Zoom motion laboratory source",
    description: "The primary application entry for the ZoomStage v2 trajectory and surface laboratory.",
    path: "/examples/zoom-lab/app.js",
    mode: "javascript",
    backLabel: "ZoomStage",
    backPath: "/addons/zoom-stage",
    previewPath: "/examples/zoom-lab/",
    previewLabel: "Open Zoom motion lab",
  },
  "vitra-protocol-example": {
    title: "VITRA Protocol source",
    description: "The primary application entry for an Inox ZoomStage and FluxaWay Motion material narrative.",
    path: "/examples/vitra-protocol/app.js",
    mode: "javascript",
    backLabel: "ZoomStage",
    backPath: "/addons/zoom-stage",
    previewPath: "/examples/vitra-protocol/",
    previewLabel: "Open VITRA Protocol",
  },
  "full-code-editor-source": {
    title: "FullCodeEditor source",
    description: "The browser-native source for FluxaWay's full code-editor add-on.",
    path: "/dist/fluxaway-editor.js",
    mode: "javascript",
    backLabel: "FullCodeEditor",
    backPath: "/addons/full-code-editor",
  },
  "full-code-editor-readme": {
    title: "FullCodeEditor API in the README",
    description: "The project README containing the FullCodeEditor API and usage guidance.",
    path: "/README.md",
    mode: "markdown",
    backLabel: "FullCodeEditor",
    backPath: "/addons/full-code-editor",
  },
  "charts-source": {
    title: "FluxaWay Charts source",
    description: "The browser-native source for FluxaWay charts and dashboard components.",
    path: "/dist/fluxaway-charts.js",
    mode: "javascript",
    backLabel: "FluxaWay Charts",
    backPath: "/addons/fluxaway-charts",
  },
  "dashboard-example": {
    title: "Dashboard example source",
    description: "The primary application entry for the FluxaWay charts dashboard example.",
    path: "/examples/dashboard/app.js",
    mode: "javascript",
    backLabel: "FluxaWay Charts",
    backPath: "/addons/fluxaway-charts",
    previewPath: "/examples/dashboard/",
    previewLabel: "Open dashboard",
  },
  "drug-recalls-example": {
    title: "Drug recalls example source",
    description: "The primary application entry for the drug-recall analytics example.",
    path: "/examples/drug-recalls/app.js",
    mode: "javascript",
    backLabel: "FluxaWay Charts",
    backPath: "/addons/fluxaway-charts",
    previewPath: "/examples/drug-recalls/",
    previewLabel: "Open drug recalls",
  },
  "pipeline-canvas-source": {
    title: "PipelineCanvas source",
    description: "The browser-native source for the node and pipeline canvas add-on.",
    path: "/dist/fluxaway-canvas.js",
    mode: "javascript",
    backLabel: "PipelineCanvas",
    backPath: "/addons/pipeline-canvas",
  },
  "pipeline-canvas-readme": {
    title: "PipelineCanvas API in the README",
    description: "The project README containing the PipelineCanvas API and usage guidance.",
    path: "/README.md",
    mode: "markdown",
    backLabel: "PipelineCanvas",
    backPath: "/addons/pipeline-canvas",
  },
});

export function sourceDocumentFor(slug) {
  return SOURCE_DOCUMENTS[slug] ?? null;
}
