// Generated by fetch_photos.py — do not hand-edit; rerun the script instead.
export const PHOTOS = [
  {
    "id": "photo-14",
    "src": "./photos/photo-14.jpg",
    "title": "Rocky coast",
    "category": "Landscapes",
    "author": "Paul Jarvis",
    "sourceUrl": "https://unsplash.com/photos/IQ1kOQTJrOQ",
    "width": 760,
    "height": 507
  },
  {
    "id": "photo-29",
    "src": "./photos/photo-29.jpg",
    "title": "Snow-capped mountain range",
    "category": "Landscapes",
    "author": "Go Wild",
    "sourceUrl": "https://unsplash.com/photos/V0yAek6BgGk",
    "width": 760,
    "height": 507
  },
  {
    "id": "photo-38",
    "src": "./photos/photo-38.jpg",
    "title": "Trail in the sky",
    "category": "Landscapes",
    "author": "Allyson Souza",
    "sourceUrl": "https://unsplash.com/photos/JabLtzJl8bc",
    "width": 760,
    "height": 570
  },
  {
    "id": "photo-69",
    "src": "./photos/photo-69.jpg",
    "title": "Tracks in the mist",
    "category": "Landscapes",
    "author": "Alexander Shustov",
    "sourceUrl": "https://unsplash.com/photos/SITaCHf7jjg",
    "width": 760,
    "height": 505
  },
  {
    "id": "photo-112",
    "src": "./photos/photo-112.jpg",
    "title": "Golden field",
    "category": "Landscapes",
    "author": "Zugr",
    "sourceUrl": "https://unsplash.com/photos/kmF_Aq8gkp0",
    "width": 760,
    "height": 507
  },
  {
    "id": "photo-77",
    "src": "./photos/photo-77.jpg",
    "title": "Tropical pier",
    "category": "Landscapes",
    "author": "May Pamintuan",
    "sourceUrl": "https://unsplash.com/photos/j9nfqTi5T5o",
    "width": 760,
    "height": 514
  },
  {
    "id": "photo-45",
    "src": "./photos/photo-45.jpg",
    "title": "Thai tuk-tuk",
    "category": "Cities",
    "author": "Alan Haverty",
    "sourceUrl": "https://unsplash.com/photos/-XA-fTYYfV0",
    "width": 760,
    "height": 426
  },
  {
    "id": "photo-61",
    "src": "./photos/photo-61.jpg",
    "title": "Old town rooftops",
    "category": "Cities",
    "author": "Alex",
    "sourceUrl": "https://unsplash.com/photos/zMz14hsbpuU",
    "width": 760,
    "height": 570
  },
  {
    "id": "photo-87",
    "src": "./photos/photo-87.jpg",
    "title": "Bench by the dock",
    "category": "Cities",
    "author": "Barcelona",
    "sourceUrl": "https://unsplash.com/photos/o697BgRH_-M",
    "width": 760,
    "height": 570
  },
  {
    "id": "photo-102",
    "src": "./photos/photo-102.jpg",
    "title": "Fresh raspberries",
    "category": "Details",
    "author": "Ben Moore",
    "sourceUrl": "https://unsplash.com/photos/pJILiyPdrXI",
    "width": 760,
    "height": 570
  },
  {
    "id": "photo-52",
    "src": "./photos/photo-52.jpg",
    "title": "Boards in the sun",
    "category": "Details",
    "author": "Cierra",
    "sourceUrl": "https://unsplash.com/photos/57vHdjeZ0yg",
    "width": 760,
    "height": 506
  },
  {
    "id": "photo-96",
    "src": "./photos/photo-96.jpg",
    "title": "Controller in the dark",
    "category": "Details",
    "author": "Pawel Kadysz",
    "sourceUrl": "https://unsplash.com/photos/CuFYW1c97w8",
    "width": 760,
    "height": 507
  }
];
