#!/usr/bin/env python3
"""One-time setup helper — NOT part of the running example.

Downloads a small curated set of free-to-use photos from Picsum
(https://picsum.photos, sourced from real Unsplash photographers, free to
reuse) into ./photos/, and (re)writes ./data.js with their metadata so the
example stays a plain static site with no runtime fetches.

Run again any time to refresh the set. Requires internet access; the example
itself does not (everything it needs is downloaded into this folder).

    python3 fetch_photos.py
"""
import json
import os
import urllib.request

DISPLAY_WIDTH = 760
HERE = os.path.dirname(os.path.abspath(__file__))
PHOTOS_DIR = os.path.join(HERE, "photos")

# (picsum id, title, category) — titles/categories are written by us based on
# what each photo actually shows (Picsum's API has no content descriptions);
# only the photo itself and the author credit are sourced from Picsum/Unsplash.
PHOTOS = [
    (14, "Rocky coast", "Landscapes"),
    (29, "Snowy mountain range", "Landscapes"),
    (38, "Sky trail", "Landscapes"),
    (69, "Tracks in the mist", "Landscapes"),
    (112, "Golden field", "Landscapes"),
    (77, "Tropical pier", "Landscapes"),
    (45, "Thai tuk-tuk", "Cities"),
    (61, "Old town rooftops", "Cities"),
    (87, "Bench by the dock", "Cities"),
    (102, "Fresh raspberries", "Details"),
    (52, "Boards in the sun", "Details"),
    (96, "Controller in the dark", "Details"),
]


def fetch_json(url):
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)


def main():
    os.makedirs(PHOTOS_DIR, exist_ok=True)
    entries = []

    for photo_id, title, category in PHOTOS:
        info = fetch_json(f"https://picsum.photos/id/{photo_id}/info")
        ratio = int(info["height"]) / int(info["width"])
        height = round(DISPLAY_WIDTH * ratio)

        filename = f"photo-{photo_id}.jpg"
        dest = os.path.join(PHOTOS_DIR, filename)
        image_url = f"https://picsum.photos/id/{photo_id}/{DISPLAY_WIDTH}/{height}"

        if os.path.exists(dest):
            print(f"Already have {filename} — skipping download (photo by {info['author']})")
        else:
            print(f"Downloading {filename} — \"{title}\" (photo by {info['author']})")
            urllib.request.urlretrieve(image_url, dest)

        entries.append({
            "id": f"photo-{photo_id}",
            "src": f"./photos/{filename}",
            "title": title,
            "category": category,
            "author": info["author"],
            "sourceUrl": info["url"],
            "width": DISPLAY_WIDTH,
            "height": height,
        })

    data_js = (
        "// Generated by fetch_photos.py — do not hand-edit; rerun the script instead.\n"
        "export const PHOTOS = "
        + json.dumps(entries, ensure_ascii=False, indent=2)
        + ";\n"
    )

    with open(os.path.join(HERE, "data.js"), "w", encoding="utf-8") as fh:
        fh.write(data_js)

    print(f"\n{len(entries)} photos saved to {PHOTOS_DIR}")
    print("data.js updated with metadata (title, author, category, dimensions).")


if __name__ == "__main__":
    main()
